# Generated by Django 6.1 on 2026-09-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
