# Generated by Django 6.1 on 2026-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_locked_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lockscreen_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
