# Generated by Django 6.1 on 2026-09-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_lockscreen_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercustomer',
            name='user',
        ),
    ]
