# Generated by Django 6.1 on 2026-09-09 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_useradmin_user_remove_usercustomer_user'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BRANCH_ADMIN', 'Branch Admin'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], max_length=20),
        ),
        migrations.DeleteModel(
            name='UserAdmin',
        ),
        migrations.DeleteModel(
            name='UserCustomer',
        ),
    ]
