# Generated by Django 6.1 on 2026-09-10 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_company_instance_and_more'),
        ('company', '0002_company_company_type_instance_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_branch', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_company', to='company.company'),
        ),
    ]
