# Generated by Django 6.1 on 2026-09-09 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datamanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_crn', models.CharField(max_length=20)),
                ('company_registered_name', models.CharField(max_length=100)),
                ('company_short_name', models.CharField(max_length=70)),
                ('registration_number', models.CharField(max_length=30)),
                ('license_number', models.CharField(max_length=30, null=True)),
                ('registration_date', models.DateField()),
                ('state_of_recognitation', models.CharField(max_length=250)),
                ('company_website', models.CharField(max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_available_24_7', models.BooleanField(default=False)),
                ('time_from', models.TimeField(null=True)),
                ('time_to', models.TimeField(null=True)),
                ('pincode', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('company_description', models.TextField(null=True)),
                ('company_icon', models.ImageField(upload_to='company_icon')),
                ('company_logo', models.ImageField(upload_to='company_logo')),
                ('company_cover', models.ImageField(null=True, upload_to='company_cover')),
                ('establish_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanagement.area')),
                ('city_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanagement.city')),
                ('country_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanagement.country')),
                ('state_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanagement.state')),
            ],
        ),
    ]
