# Generated by Django 6.1 on 2026-09-10 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('datamanagement', '0002_companytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanagement.companytype'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_id', models.CharField(max_length=20)),
                ('branch_full_name', models.CharField(max_length=100)),
                ('branch_short_name', models.CharField(max_length=70)),
                ('is_main_branch', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(max_length=30)),
                ('license_number', models.CharField(max_length=30, null=True)),
                ('registration_date', models.DateField()),
                ('state_of_recognitation', models.CharField(max_length=250)),
                ('branch_website', models.CharField(max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_available_24_7', models.BooleanField(default=False)),
                ('time_from', models.TimeField(null=True)),
                ('time_to', models.TimeField(null=True)),
                ('pincode', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('branch_description', models.TextField(null=True)),
                ('branch_icon', models.ImageField(upload_to='branch_icon')),
                ('branch_logo', models.ImageField(upload_to='branch_logo')),
                ('branch_cover', models.ImageField(null=True, upload_to='branch_cover')),
                ('establish_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanagement.area')),
                ('branch_type_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanagement.companytype')),
                ('city_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanagement.city')),
                ('country_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanagement.country')),
                ('state_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanagement.state')),
            ],
        ),
    ]
