# Generated by Django 6.1 on 2026-09-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_company_type_instance_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='company_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.company'),
        ),
    ]
